# Generated by Django 2.1.15 on 2020-06-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuserinfo',
            name='age',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeuserinfo',
            name='user_id',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
